export const ACCOUNT_FORM_NAME = 'account'
export const LOGIN_FORM_NAME = 'login'
export const SIGNUP_FORM_NAME = 'signup'
export const BUSINESS_SIGNUP_FORM_NAME = 'businessSignup'
export const CUSTOMER_SIGNUP_FORM_NAME = 'customerSignup'
export const NEW_PROJECT_FORM_NAME = 'newProject'
export const ADD_FOOD_FORM_NAME = 'addFood'
