export const LIST_PATH = '/projects'
export const FOOD_MENU_PATH = '/menu'
export const BOOK_A_TABLE = '/book-a-table'
export const ACCOUNT_PATH = '/account'
export const LOGIN_PATH = '/login'
export const SIGNUP_PATH = '/signup'
